// Get all blogs
export const BLOGS_LIST_REQUEST = "BLOGS_LIST_REQUEST";
export const BLOGS_LIST_SUCCESS = "BLOGS_LIST_SUCCESS";
export const BLOGS_LIST_FAIL = "BLOGS_LIST_FAIL";

// Get one user's all blogs by user's ID
export const USER_BLOGS_REQUEST = "USER_BLOGS_REQUEST";
export const USER_BLOGS_SUCCESS = "USER_BLOGS_SUCCESS";
export const USER_BLOGS_FAIL = "USER_BLOGS_FAIL";
export const USER_BLOGS_RESET = "USER_BLOGS_RESET";

// Get one blog article
export const BLOG_DETAIL_REQUEST = "BLOG_DETAIL_REQUEST";
export const BLOG_DETAIL_SUCCESS = "BLOG_DETAIL_SUCCESS";
export const BLOG_DETAIL_FAIL = "BLOG_DETAIL_FAIL";

// Create one blog article
export const BLOG_CREATE_REQUEST = "BLOG_CREATE_REQUEST";
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS";
export const BLOG_CREATE_FAIL = "BLOG_CREATE_FAIL";
export const BLOG_CREATE_RESET = "BLOG_CREATE_RESET";

// Update one blog article
export const BLOG_UPDATE_REQUEST = "BLOG_UPDATE_REQUEST";
export const BLOG_UPDATE_SUCCESS = "BLOG_UPDATE_SUCCESS";
export const BLOG_UPDATE_FAIL = "BLOG_UPDATE_FAIL";
export const BLOG_UPDATE_RESET = "BLOG_UPDATE_RESET";

// Delete one blog article
export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST";
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
export const BLOG_DELETE_FAIL = "BLOG_DELETE_FAIL";

// add comment to one blog
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

// delete comment to one blog
export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
